### ISSUE TITLE
Open file in RV

### ISSUE THREAD

**Issue by jasonhuang1115** [mb0rt/Nuke-NodeHelpers#2]
Hi,

Would like to report another issue.

As I click on Open file in RV with a read node selected, I got this message printed in Nuke's console:
```
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mb0rt** [comment]
Hi Jason, awesome, thanks for letting me know!
I updated and tested(on windows) seems fine now. Make sure you have RV is on "C:/Program Files/Shotgun/RV-7.2.1/bin/rv.exe". If you have a newer or older version of RV, you will have to change your nuke's menu.py, line 35 ('rv_paths' variable) and add a proper one(probably, just need to change '7.2.1' to another version.

**Comment by jasonhuang1115** [comment]
Sweet! Just tested it and it works. Thank you!
